#-- prefix key
set-option -g prefix M-a


#-- general
set -sg escape-time 0
set -g mouse on
set -g allow-rename off
set -s set-clipboard on
set -sa terminal-features ',*:clipboard'
set -sa terminal-features ',*:RGB'


#-- key target
set -g key-table root
bind -T root M-r set -g key-table remote \; set -g status on
bind -T remote M-r set -g key-table root \; set -g status off


#-- window handling
bind -n M-C new-window
bind -n M-N next-window
bind -n M-P previous-window


#-- pane handling
bind -n M-e split-window -h
bind -n M-o split-window -v

bind -n M-h resize-pane -L 5
bind -n M-j resize-pane -D 3
bind -n M-k resize-pane -U 3
bind -n M-l resize-pane -R 5

bind -n M-H select-pane -L
bind -n M-J select-pane -t:.+
bind -n M-K select-pane -t:.-
bind -n M-L select-pane -R

bind -n M-p swap-pane -U
bind -n M-n swap-pane -D

#-- local only
bind -n M-1 switch-client -t :code
bind -n M-2 switch-client -t :cli
bind -n M-d switch-client -t default
bind -n M-s if-shell '[ "#S" = "default" ]' 'switch-client -l' ''

bind -n M-f display-popup -E 'bash ~/dev/dotfiles/tmux/project-manager.sh open-project'
bind -n M-F display-popup -E 'bash ~/dev/dotfiles/tmux/project-manager.sh select-session'


#-- remote status helper
set -g status-left-length 80
set -g status-right-length 80
set -g status-style bg=colour97,fg=colour255
set -g status-left '[remote] #{pane_title} '
set -g status-right '[option+r] switch to local '
set -g window-status-format ''
set -g window-status-current-format ''
set -g window-status-separator ''


#-- theme
set -g status off
set -g pane-border-style fg=colour239
set -g pane-active-border-style fg=cyan
set -g popup-border-style fg=colour239
